name: build project

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      uses: actions/checkout@v4


  job2:
    runs-on: macos-latest
    steps:
    - name: step2
      uses: actions/checkout@v4
  job3:
    runs-on: windows-latest
    steps:
    - name: step3
      run: echo hello!     
